version: '3.9'

services:
    doctron:
        image: lampnick/doctron
        ports:
            - "8080"
        restart: always
    nginx:
        image: nginx:alpine
        ports:
            - "8000:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        restart: always
    preview:
        build: .
        ports:
            - "3000"
        restart: always

